### ISSUE TITLE
NPEs appearing in log

### ISSUE THREAD

**Issue by cnenning** [cnenning/go-artifactory-scm-plugin#19]
I observed NPEs like following. I usually happens when a new material is created and stops after artifacts have been downloaded via that material. Url is stripped but correct.

    .... ArtifactoryScmPlugin:77 - ERROR!
        request name: latest-revision
        request body: {"scm-configuration":{
                                   "version_only":{"value":""},
                                   "password":{"value":""},
                                   "version_regex":{"value":""},
                                   "dummy_id":{"value":""},
                                   "pattern":{"value":"...."},
                                   "url":{"value":"...."},
                                   "username":{"value":""}
                               },"scm-data":{},"flyweight-folder":"...."}
    java.lang.NullPointerException
        at com.github.cnenning.artiscm.AbstractArtifactoryPlugin.buildRevisionJson(AbstractArtifactoryPlugin.java:433)
        at com.github.cnenning.artiscm.ArtifactoryScmPlugin.handleLatestRevision(ArtifactoryScmPlugin.java:172)
        at com.github.cnenning.artiscm.ArtifactoryScmPlugin.handleApiRequest(ArtifactoryScmPlugin.java:64)
        at com.github.cnenning.artiscm.AbstractArtifactoryPlugin.handle(AbstractArtifactoryPlugin.java:193)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:187)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:182)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
        .....

**Comment by cnenning** [comment]
I'm closing this for now. Let's see if logged data gives us more insight.
