### ISSUE TITLE
Seems to pull random versions

### ISSUE THREAD

**Issue by mattcotton-justgiving** [cnenning/go-artifactory-scm-plugin#21]
I have artifactory structure like this:

/1.0.9/someFile.gzip
/1.0.10/someFile.gzip
...
/1.0.24/someFile.gzip

Some pipelines pull correctly the latest version, 1.0.24, but others seem to pull randomly from previous versions. I've checked they don't specify a version regex. I can't understand how to get the pipelines all pulling the latest version consistently.

**Comment by cnenning** [comment]
two things come to my mind:
- upload timestamp (this issue happens when older versions are uploaded after new ones)
- exceptions due to network issues (I have seen similar behavior of go when there have been network issues, like timeouts, when pulling artifactory for new versions, check logs for that please)

See this link about how to configure and find go plugin log files:
https://developer.gocd.org/current/writing_go_plugins/go_plugins_basics.html

**Comment by mattcotton-justgiving** [comment]
From the plugin-artifactory-scm.log on the server I see the following error. This suggests the plugin is asking artifactory for all revisions since `2017-11-11T16:17:00.000Z` and then timing out.

```
2017-12-19 15:19:49,817 ERROR [91@MessageListener for MaterialUpdateListener] ArtifactoryScmPlugin:77 - ERROR!
	request name: latest-revisions-since
	request body: {"scm-configuration":{"dummy_id":{"value":"25"},"url":{"value":"http://artifactory.justgiving.com:80/artifactory/int-Files/justgiving/helm/"}},"scm-data":{},"flyweight-folder":"/mnt/go-server/pipelines/flyweight/6dd351be-8313-411b-96e8-929fa61fbac2","previous-revision":{"revision":"1.0.10","timestamp":"2017-11-11T16:17:00.000Z","data":{}}}
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.github.cnenning.artiscm.ArtifactoryClient.downloadHtml(ArtifactoryClient.java:124)
	at com.github.cnenning.artiscm.ArtifactoryClient.children(ArtifactoryClient.java:264)
	at com.github.cnenning.artiscm.ArtifactoryClient.files(ArtifactoryClient.java:259)
	at com.github.cnenning.artiscm.ArtifactoryClient.filesForRev(ArtifactoryClient.java:250)
	at com.github.cnenning.artiscm.ArtifactoryClient.revisions(ArtifactoryClient.java:232)
	at com.github.cnenning.artiscm.ArtifactoryClient$2.callback(ArtifactoryClient.java:208)
	at com.github.cnenning.artiscm.ArtifactoryClient$2.callback(ArtifactoryClient.java:204)
	at com.github.cnenning.artiscm.ArtifactoryClient.downloadHtml(ArtifactoryClient.java:134)
	at com.github.cnenning.artiscm.ArtifactoryClient.latestRevisionsSince(ArtifactoryClient.java:204)
	at com.github.cnenning.artiscm.ArtifactoryScmPlugin.handleLatestRevisionsSince(ArtifactoryScmPlugin.java:185)
	at com.github.cnenning.artiscm.ArtifactoryScmPlugin.handleApiRequest(ArtifactoryScmPlugin.java:66)
	at com.github.cnenning.artiscm.AbstractArtifactoryPlugin.handle(AbstractArtifactoryPlugin.java:193)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:187)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:182)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:182)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.latestModificationSince(SCMExtension.java:123)
	at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.modificationsSince(PluggableSCMMaterialPoller.java:78)
	at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.modificationsSince(PluggableSCMMaterialPoller.java:47)
	at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:109)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:55)
	at com.thoughtworks.go.server.materials.PluggableSCMMaterialUpdater.insertLatestOrNewModifications(PluggableSCMMaterialUpdater.java:61)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:145)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:137)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:104)
	at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
	at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:101)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:50)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:30)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cnenning** [comment]
Alright, let's fix it 😉 

You can set timeouts to higher values on go plugin admin page. Next to each plugin is a cogwheel icon. That leads to a plugin settings page.

After an exception occurred for a material go stops polling for new versions. To re-enable it you need to re-create the material. As go prohibits to create the same material a 2nd time this plugin has the `dummy  id` field. You can re-create your materials by using a different value as `dummy  id`.

**Comment by mattcotton-justgiving** [comment]
I've set the following artifactory-scm options:
Socket Timeout: -1
Connection Pool Size:5

I changed the DummyId field in the material from 25 to 26.
This triggered a new build but the version being brought back is still "1.0.10", not "1.0.25".
Any other ideas?

**Comment by cnenning** [comment]
> I changed the DummyId field in the material from 25 to 26.

You must create a new material with a different name. By default go refuses to save a material which has same values as an existing one. Thus you must use a different value for DommyId in the new material.

**Comment by mattcotton-justgiving** [comment]
OK I deleted the old material, created a new one with a different name and different dummy_id. The pipeline is still pulling version '1.0.10' not the latest.

This is the new scm definition from config XML:
```
<scm id="2af34020-a98e-4053-834a-3339c6cf0ff6" name="campaigns-api-deploy-2">
      <pluginConfiguration id="artifactory-scm" version="1" />
      <configuration>
        <property>
          <key>dummy_id</key>
          <value>37</value>
        </property>
        <property>
          <key>url</key>
          <value>http://xxx.com/artifactory/int-Files/justgiving/helm/</value>
        </property>
      </configuration>
    </scm>
```

**Comment by cnenning** [comment]
Go sends plugin preferences to plugin on server start only. So when you changed timeout you have to restart go-server. There should be a message in log with timeout value.

**Comment by cnenning** [comment]
I added a section about some of this in Readme. Hopefully next one will find it faster.
